### ISSUE TITLE
Not support Laravel 5.6?

### ISSUE THREAD

**Issue by MatanYed** [Torann/laravel-currency#101]
`php artisan currency:update` return success response but actually there is nothing in currencies table
maybe not support laravel 5.6?

**Comment by zymawy** [comment]
@MatanYadaev  Did You Manage It ?

**Comment by MatanYadaev** [comment]
@zymawy I just didn't execute the correct command. The correct command was:
`php artisan currency:update -o` (for OpenExchengeRate)

**Comment by zymawy** [comment]
@MatanYadaev Welcome, This Is Waird I Have Try It but getting 

```shell 
The "-o" option does not exist.
```
