### ISSUE TITLE
Remove this shithole plugin.

### ISSUE THREAD

**Issue by shahidkarimi** [Torann/laravel-currency#119]
This pluggin is creating lot of problem for everyone using it. Remove this shit from git asap.

**Comment by petyots** [comment]
@shahidkarimi What's the issue ?

**Comment by chistel** [comment]
@shahidkarimi do you have to be insensitive?? if it doesn't work for you, you move else where.

**Comment by chistel** [comment]
> 
> 
> This pluggin is creating lot of problem for everyone using it. Remove this shit from git asap.

@shahidkarimi do you have to be insensitive?? if it doesn't work for you, you move else where.
