### ISSUE TITLE
Missing some currencies

### ISSUE THREAD

**Issue by nlemsieh** [Torann/laravel-currency#15]
How can I add more currencies?
---
I think It's will be great to add more currencies using artisan like this : 
```php
php artisan currency:add --currencies=BDT,BHD
```

or/and using code : 

```php 
Currency::add([
'BDT', 'BHD'
]);
```
And this will fetch for data from the Finance yahoo!  and update currency table.

Thanks for sharing

**Comment by natsu90** [comment]
+1

**Comment by Torann** [comment]
With the version 0.2 you can use the `currency()` helper function to add/find/update/delete currencies. 

View the documentation for more information: http://lyften.com/projects/laravel-currency/doc/methods.html
