### ISSUE TITLE
Currency::hasCurrency() return always true

### ISSUE THREAD

**Issue by nlemsieh** [Torann/laravel-currency#16]
I tried to use
```php
Currency::hasCurrency('EUR')
```

But it seams to return always true.
Then I adopted this solution : 

```php

public function hasCurrency($currency)
	{
    return $currency == $this->getCurrencyCode();
    // return isset($this->currencies[$currency]);
  	}
```

**Comment by Torann** [comment]
Your approach will only check if the current currency matches the one you passed to the function. The `hasCurrency` is meant to check if the currency you pass to it is in the system.
