### ISSUE TITLE
"php artisan currency:update" command rise an Exception

### ISSUE THREAD

**Issue by luca83** [Torann/laravel-currency#21]
The problem is on the the currecy table field 'value'. At the moment is a DOUBLE(15,8) but rise an error on the value 1.00 that is the default currency value, that because try to store a value that contain only 2 decimal. I resolved this changing the field into DECIMAL(17,2) that actually is more precise than DOUBLE. Of course in this way the value is rounded! what you think?

**Comment by Torann** [comment]
Strange, I have yet to run into this.
