### ISSUE TITLE
Feature Request: Rounding

### ISSUE THREAD

**Issue by hiyahin** [Torann/laravel-currency#23]
It would be great if rounding could be implemented into the Currency:format() function, including to which point it would round to (hundreds, tens, unit, 1 decimal point, etc.) and whether to always round up (ceil), always round down (floor) or round to the nearest point.

**Comment by Torann** [comment]
Pull request merged

**Comment by azeos** [comment]
Is there any rounding option in v1.0.14? Thx for the package.

**Comment by plicas** [comment]
Why this was featured removed ?

**Comment by davidgv88** [comment]
Feature Removed?
