### ISSUE TITLE
 SQLSTATE[01000]: Warning: 1265 Data truncated for column 'value' at row 1

### ISSUE THREAD

**Issue by kwab** [Torann/laravel-currency#25]
Using:
- Laravel Framework version 4.2.11
- PHP Version => 5.6.1 (on Windows)
- MYSQL 5.6.21 (on Windows)
- "torann/currency": "dev-master"

Resolved by converting value to a number on line 103

    // Update each rate
    foreach ($lines as $line)
    {
	   $code = substr($line, 4, 3);
	   $value = substr($line, 11, 6) * 1.00; //force conversion to number

	   if ($value)
			{
				$this->app['db']->table($this->table_name)
					->where('code', $code)
					->update(array(
						'value' 		=> $value,
						'updated_at'	=> new \DateTime('now'),
					));
			}
    }

**Comment by Torann** [comment]
Added https://github.com/Torann/laravel-currency/commit/5749a59b8eee72a60dd0cb899e8f40c48e41fe7b
