### ISSUE TITLE
Symfony \ Component \ Debug \ Exception \ FatalErrorException Using $this when not in object context

### ISSUE THREAD

**Issue by bjornetzold** [Torann/laravel-currency#26]
![screen shot 2014-12-01 at 11 59 45](https://cloud.githubusercontent.com/assets/9569739/5244637/9b3633cc-7951-11e4-9748-48645e2adae7.png)

I get this error message, after the installation

**Comment by Torann** [comment]
Laravel Currency only supports PHP 5.4 and above with the new version 0.2 only supporting PHP 5.5.9 and above. This has been fixed in the composer.json file to warn users that try to install it on a system that can't support it.
