### ISSUE TITLE
How can i get all available currencies ?

### ISSUE THREAD

**Issue by mogahead** [Torann/laravel-currency#28]
I need to view all available currencies , how can i do that ?

**Comment by canfiax** [comment]
Agreed. Package should include all currencies by default.

Should follow iso4217: http://www.xe.com/iso4217.php

**Comment by masterakado** [comment]
You could try ~~~ \DB::table('currency')->get() ~~~ to get all curencies it actually depends on your configuration though, how you have named your currency table

**Comment by Torann** [comment]
Version 0.2 now comes with a helper function `currency()`

To get all currencies:

```php
currency()->setCacheCurrencies();
```

This will return an array of all currencies:

```php
[
  "USD" => [
    "id" => 1
    "title" => "U.S. Dollar"
    "symbol_left" => "$"
    "symbol_right" => ""
    "decimal_place" => 2
    "value" => 1.0
    "decimal_point" => "."
    "thousand_point" => ","
    "code" => "USD"
  ]
  "EUR" => [
    "id" => 2
    "title" => "Euro"
    "symbol_left" => "€"
    "symbol_right" => ""
    "decimal_place" => 2
    "value" => 0.8912
    "decimal_point" => "."
    "thousand_point" => ","
    "code" => "EUR"
  ]
]
```
