### ISSUE TITLE
Laravel 5 support?

### ISSUE THREAD

**Issue by mendrinos** [Torann/laravel-currency#29]

**Comment by canfiax** [comment]
Yeah! Great package, but lacks L5 support.

**Comment by matohavo** [comment]
+1

**Comment by dakshhmehta** [comment]
I'm working on a project, and converting it to support Laravel 5. Will send PR soon

**Comment by Torann** [comment]
In progress now...

**Comment by Torann** [comment]
A new version is released

- Support Laravel 5
- Update the code to PSR-4 compliant
- Add custom storage drivers
- Removed cookie support
- Removed Blade custom extension (use helper function `currency()`)

With the custom storage drivers we are no longer restricted to a single type of currency storage. Right now it supports:

- Database with the option to set a specific connection other than the system default
- Laravel Filesystem with the option to specify a disk other than the system default

For more documentation visit http://lyften.com/projects/laravel-currency
