### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by halenharper** [Torann/laravel-currency#37]
Hi!
Can you make currency converter in this package, like
```
$rate = currency($price, 'USD/EUR');
// $rate = ['value'=> $value, 'date' => $date]
$rate->getValue(); // 0.8768
//or
$price = 1;
$convert = currency($price, 'USD', 'EUR');
$convert = 0.8768;
```
if user default currency is same as in config file I use $inverse method. But if I use for each user different default currency this method can not be used.

**Comment by Torann** [comment]
Sorry, but I'm not entirely sure what you're asking

**Comment by Torann** [comment]
Looking this over again I think I get it. The conversation part of the package was a bit confusing. It's been fully rewritten in [version 1.0](https://github.com/Torann/laravel-currency/tree/1.0). I should have it fully released next week sometime
