### ISSUE TITLE
Registering as singleton?

### ISSUE THREAD

**Issue by sebestenyb** [Torann/laravel-currency#42]
I wonder if the service should be registered as singleton.

The current `$this->app->bind` doesn't seem to work for me, the currency got reset to null in the service.

```
public function registerCurrency()
{
    $this->app->singleton('currency', function ($app) {
        $config = $app->config->get('currency', []);
        return new Currency($config, $app['cache']);
    });
}
```

**Comment by Torann** [comment]
Yeah, I was running into the same problem. It's been fixed in v0.3.2 

https://github.com/Torann/laravel-currency/releases/tag/0.3.2
