### ISSUE TITLE
The use of Reflash() in middle-ware has some unwanted consequences 

### ISSUE THREAD

**Issue by azrahn** [Torann/laravel-currency#44]
Hi,
In the MiddleWare you use reflash method.
This causes other flash messages also to reflash and they keep being reflashed for ever.
I suggest changing
`$request->getSession()->reflash();`
to 
`$request->getSession()->keep('currency);`

**Comment by lyonlim** [comment]
This!

I almost decided to re-import my app onto a fresh Laravel installation because of this issue.
There's also the issue with the Middleware exception.

At this point, since I don't need the option to switch currency, I've disabled the Middleware and fixed both issues as such.

**Comment by Torann** [comment]
You have to ensure the middleware is after `\Illuminate\Session\Middleware\StartSession::class` in the `app/Http/Kernel.php` file.

**Comment by azrahn** [comment]
I have checked and the middleware is after \Illuminate\Session\Middleware\StartSession::class in the app/Http/Kernel.php file. Problem is still there.

**Comment by Torann** [comment]
Ok, I just moved to `keep` in v0.3.4. Works perfectly thank you 👍
