### ISSUE TITLE
Error in Middleware and no formatting of default currency

### ISSUE THREAD

**Issue by matbeard** [Torann/laravel-currency#45]
When I add the Middleware to Kernel.php I get the following error on all pages:

    FatalThrowableError in CurrencyMiddleware.php line 29:
    Call to a member function get() on null

Also, the default currency (which I have set to GBP) is not formatted. If I use `Currency::format(15)` the result is simply `15`. If I specify the currency: `Currency::format(15,'GBP')` it is properly formatted as `£15.00`. Conversion is working.

**Comment by azrahn** [comment]
Yes I had the same . I had to use 
`Currency::format($amount,Session::get('currency')`
to get the format working.

**Comment by golinmarq** [comment]
How do you solve the fatal throwable error?

**Comment by azrahn** [comment]
did you run the migration?

**Comment by golinmarq** [comment]
Sure

**Comment by dakshhmehta** [comment]
I face the same problem, but why isnt it working with helper function currency which is doing same thing? Isn't it?

**Comment by lyonlim** [comment]
I realised the issue with the exception is because `\Illuminate\Session\Middleware\StartSession::class,` has not started. In 5.2, this is under $middlewareGroups in Http\Kernel.

Moving `\Torann\Currency\Middleware\CurrencyMiddleware::class,` to $middlewareGroups fixes this.

**Comment by DrudgeRajen** [comment]
@lyonlim :+1:

**Comment by shafaqatrazaa** [comment]
@azrahn where should I add this ??
Currency::format($amount,Session::get('currency')

**Comment by shafaqatrazaa** [comment]
@lyonlim it didn't worked

**Comment by shafaqatrazaa** [comment]
![image](https://user-images.githubusercontent.com/35936247/36609718-aea6e99c-18ef-11e8-93c8-dd585469560c.png)
