### ISSUE TITLE
Specify 'base' currency when updating database

### ISSUE THREAD

**Issue by matbeard** [Torann/laravel-currency#46]
When I ran the `currency:update` command on my local testing server, the resulting base currency was GBP (that is, the one that got a rate of 1.00000).

However, the same command on our production server resulted in USD getting a value of 1.00000.

Is there a way to ensure the downloaded values are relative to the correct 'base' currency?

**Comment by Torann** [comment]
Hmmm. Is the config file updated on the production server? Also what service are you using to get the exchange rates?

**Comment by Torann** [comment]
Currency management commands have been cleaned up in v1.0. Give that a try
