### ISSUE TITLE
How do I unistall this package?

### ISSUE THREAD

**Issue by golinmarq** [Torann/laravel-currency#47]
I'm trying to unistall this package using `composer remove torann/currency` but I get this error:

>[RuntimeException]                                                                                                                                  >           
>  Error Output: PHP Fatal error:  Class 'Torann\Currency\CurrencyServiceProvider' not found in home/myUser/WebProjects/myProject/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

How can I clean delete this package?

**Comment by azrahn** [comment]
remove from composer.json
run `composer update`
