### ISSUE TITLE
Calling Commands from Controller do not work

### ISSUE THREAD

**Issue by apocalyarts** [Torann/laravel-currency#62]
In one of my controllers I want to call Artisan::call('currency:update') but it does not work. The Exception:

CommandNotFoundException in Application.php line 490:
There are no commands defined in the "currency" namespace.

However, in a different part of my application (a Seeder class), Artisan::call('currency:update') works.

So what is causing the crash in the controller?

**Comment by apocalyarts** [comment]
I had to manually add all the console commands from the package to Console/Kerne.php

If this cannot be fixed withing the package, please expand the docs.

**Comment by BrunoTeixeiraNavila** [comment]
@apocalyarts Can you share how did you do it for a newbie or share the code please? Thanks

**Comment by apocalyarts** [comment]
`
// In App\Console\Kernel, make sure to add the classes to the $commands array:
protected $commands = [
    \Torann\Currency\Console\Update::class,
    \Torann\Currency\Console\Cleanup::class,
    \Torann\Currency\Console\Manage::class
];
`

**Comment by BrunoTeixeiraNavila** [comment]
@apocalyarts Tks, worked like a charm

**Comment by veneliniliev** [comment]
https://github.com/Torann/laravel-currency/blob/master/src/CurrencyServiceProvider.php#L18

remove this condition and all will work fine

**Comment by qeifar** [comment]
@apocalyarts  ThankkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkYouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu 😄 🤣 😆

**Comment by Torann** [comment]
If you are updating the exchange rate why not just use a cron job? That is how I have my server setup.
