### ISSUE TITLE
create currency command gives error.

### ISSUE THREAD

**Issue by BrunoTeixeiraNavila** [Torann/laravel-currency#64]
I tried the command on the documentation:

currency()->create([
			'currency_name' => 'U.S. Dollar',
			'currency_code' => 'USD',
			'currency_symbol' => '$',
			'currency_format' => '$1,0.00',
			'exchange_rate' => 1.00000000,
			'active' => 1,
		]);

I get the following error:

Undefined index: code

**Comment by Torann** [comment]
The doc was incorrect. It was for an old version. It's being updated now. Here is what it should be:

```php
currency()->create([
    'name' => 'U.S. Dollar',
    'code' => 'USD',
    'symbol' => '$',
    'format' => '$1,0.00',
    'exchange_rate' => 1.00000000,
    'active' => 1,
]);
```
