### ISSUE TITLE
Database driver will fail to create records in strict db configruations.

### ISSUE THREAD

**Issue by nCrazed** [Torann/laravel-currency#65]
Running `php artisan currency:manage add USD` will result in an INSERT query that attempts to insert an empty string (`''`) value into the integer id column which yields the following error on PostgreSQL:

> invalid input syntax for integer

and probably something similar on MySQL with relevant strict modes enabled.

This is due to [this](https://github.com/Torann/laravel-currency/blob/master/src/Drivers/Database.php#L44-L54) default array. Since your migration sets the `id` column to `auto increment` the `id` should be dropped from the default array completely.

**Comment by apocalyarts** [comment]
+1

**Comment by l3xq** [comment]
Even with the suggested fix by nCrazed, I still have same error:
```
[PDOException]
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""
```

**Comment by nCrazed** [comment]
@l3xq can paste the full error with the query that triggers it?

**Comment by l3xq** [comment]
@nCrazed Sorry it took so long to replay.
Per your instructions [removed 'id'](http://imgur.com/qW5uupN), and the [error](http://imgur.com/bl6kldT) persists.

**Comment by nCrazed** [comment]
@l3xq I see that the `id` is still present which it shouldn't be. Can you post the full stack trace to make sure that the insert is not being called from somewhere else?

As far as I can tell this is the only source of `INSERT` queries in the context of the `currency:manage add` command and the `id` is set only in that array. Without the `id` it should not be present in the query, but it's hard for me to test and confirm this assertion because the package expects to be within the context of a full Laravel application so it's impossible to test in isolation. Which is probably why there are no tests.

@Torann any plans on making the package testable without the entire laravel framework?
