### ISSUE TITLE
Error when updating to Laravel 5.4

### ISSUE THREAD

**Issue by apocalyarts** [Torann/laravel-currency#67]
It looks this package is causing errors when php artisan optimize is executed during the upgrade progress.

> php artisan optimize

  [Illuminate\Contracts\Container\BindingResolutionException]
  Unresolvable dependency resolving [Parameter #0 [ <required> array $config
  ]] in class Torann\Currency\Drivers\Database

**Comment by Torann** [comment]
Hmm, I'll have to look into it. I have yet to upgrade any of my apps.

**Comment by Torann** [comment]
You should be all set :-)
