### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by azcoppen** [Torann/laravel-currency#68]
Composer.json 

```json
"minimum-stability": "dev",
"laravel/framework": "5.3.*",
"torann/currency": "^1.0",
```

Composer update after artisan:optimize

```
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                                                           
  Type error: Too few arguments to function Torann\Currency\Drivers\Database::__construct(), 1 passed in /Users/Alex/WEBHOSTS/FHMatchL5/vendor/torann/currency/src/Currency.php on line 255 and exactly 2 expected  
```

**Comment by Torann** [comment]
I'm sorry, I think that was my fault. I was having a problem with updating it to Laravel 5.4. The update to Laravel 5.4 will still be compatible with 5.3.

This should fix it for you, run the following in you console:

Remove the old version of my package:
```
composer remove torann/currency
```

And reinstall it:
```
composer require torann/currency
```

The new version of my package is 1.0.5. I just released it, so it might take it a few minutes for you system to see it.
