### ISSUE TITLE
Correction on the currencies information for Africa (XAF and XOF)

### ISSUE THREAD

**Issue by thugyac** [Torann/laravel-currency#74]
Hello , 

Great package, we really love it and use it on our website. 
But we have a little suggestion for the currencies.php files. 
Some african currencies are incorrect. 

In Africa we XOF and XAF currencies and in your file you only add one of them. 
Plus the symbole is not "F" but "F.CFA"

I change your file in my vendor project but everytime we make an update we have to change it again, so can you please correct the fille ? 

There is what must be in the file : 

    'XAF' => [
        'name' => 'Franc CFA (XAF)',
        'symbol' => 'F.CFA',
        'format' => '1,0.00 F.CFA',
        'exchange_rate' => 0.00,
    ],
    'XOF' => [
        'name' => 'Franc CFA (XOF)',
        'symbol' => 'F.CFA',
        'format' => '1,0.00 F.CFA',
        'exchange_rate' => 0.00,
    ],

Kind regard. 
Yacoub

**Comment by Torann** [comment]
Just added them :-)
