### ISSUE TITLE
Where are preset currencies?

### ISSUE THREAD

**Issue by RalphMRivera** [Torann/laravel-currency#78]
According to the docs:

`The package comes with a set of preset currencies. To add them use the artisan manage command.`

However, my `currencies` table is empty and when I run `php artisan currency:update` nothing happens.

How can I see the presets?

**Comment by agmadt** [comment]
+1

**Comment by evianoa** [comment]
+1

**Comment by nowned** [comment]
+1 looked through the code base and can't seem to find them

**Comment by Torann** [comment]
The command `artisan currency:manage` is just a helper. It is there so that you can add and remove currencies in the DB. 

http://lyften.com/projects/laravel-currency/doc/commands.html

```
artisan currency:manage -h

Usage:
  currency:manage <action> <currency>

Arguments:
  action                Action to perform (add, update, or delete)
  currency              Code or comma separated list of codes for currencies
```

```
artisan currency:manage add AMD,USD
```

Will add Armenian Dram and US Dollar to the DB.
