### ISSUE TITLE
Precision error

### ISSUE THREAD

**Issue by rajaneeshdwivedi** [Torann/laravel-currency#81]
Great package. One suggestion is in convert(), in src\currency.php, to replace:

	$value = $amount * $to_rate * (1 / $from_rate);

with

	if ($from == $to)
		$value = $amount;
	else
		$value = ($amount * $to_rate) / $from_rate;

as this solves a precision error where, in one case, a conversion of -2800 comes back as -2799 when blindly converting back to the same currency. Also the second line has greater precision and actually also solves my particular -2799 case even without the from-to check.

**Comment by Torann** [comment]
Just implement your fix. Thanks :)
