### ISSUE TITLE
Where does "setUserCurrency($code)" store value

### ISSUE THREAD

**Issue by abhi-cognitivo** [Torann/laravel-currency#82]
Hi,

So far I have no hiccups, but I need to be able to set default currencies for users. I noticed that your documentation has reference to this end, with the **setUserCurrency($code)** method.

Question, where does Lyften actually store this data? DB, JSON? Because when I ran the Migration, it created a single Currencies table, and in Users table left untouched. 

I wanted to make sure this was proper before continuing, if you can advise. In any rate, is there a way to over ride default with a database based solution?

Thanks!

**Comment by Torann** [comment]
I just stores it in the currency instance. If you want to store it in the DB or session you will need to extend the middleware `Torann\Currency\Middleware\CurrencyMiddleware` and add what you need done in the `setUserCurrency` method. This is what I do with my sites

**Comment by abhi-cognitivo** [comment]
Great thanks
