### ISSUE TITLE
Yahoo exchange rates service discontinued

### ISSUE THREAD

**Issue by DanSorahan** [Torann/laravel-currency#86]
Updating from Yahoo Finance will now fail with the following error.

```
[ErrorException]
A non-numeric value encountered
```
This error is thrown at `src/Console/Update.php:88`.

Dumping out the response gives the following message

> array:1 [
>  0 => "<html><head><title>Yahoo! - 403 Forbidden  -- error 403</title></head><body>It has come to our attention that this service is being used in violation of the Yahoo Terms of Service.  As such, the service is being discontinued.  For all future markets and equities data research, please refer to finance.yahoo.com.</body></html>"
> ]

**Comment by Torann** [comment]
The readme was updated and Yahoo was removed as a provider 21 days ago today :-(
