### ISSUE TITLE
php artisan currency:update => Exception

### ISSUE THREAD

**Issue by hvervest** [Torann/laravel-currency#87]
php artisan currency:update leads to an exception:
[exception.log](https://github.com/Torann/laravel-currency/files/1465150/exception.log)

Updating currency exchange rates from OpenExchangeRates.org...
                                                                                                              
  [Exception]                                                                                                   
  DateTime::__construct(): Failed to parse time string (-49454009348) at position 10 (4): Unexpected character

**Comment by bhargav3** [comment]
@aemr3 how do we use this as a composer package?

**Comment by aemr3** [comment]
Hi @bhargav3, I will not publish it. Because I think repository owner @Torann will merge the changes. 
But for now you can add these lines to your composer.json file in order to get the fix;

```   
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/aemr3/laravel-currency"
    }
],
```

**Comment by Torann** [comment]
Just released a patch for this

**Comment by hvervest** [comment]
thank you
