### ISSUE TITLE
Currency format for TRY

### ISSUE THREAD

**Issue by onurkose** [Torann/laravel-currency#88]
`php artisan currency:manage add TRY` adds row to database in format "1,0.00 TL" but it should actually be "1.0,00 TL", also its name has been changed from "New Turkish Lira" to "Turkish Lira".
https://www.currency-iso.org/en/home/tables/table-a1.html

-edit:
Finally, it has a new symbol as "₺"
https://en.wikipedia.org/wiki/Turkish_lira_sign

**Comment by Torann** [comment]
Thanks. I just updated the code
