### ISSUE TITLE
Timestamp error when running update

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [Torann/laravel-currency#90]
When I run _**php artisan currency:update**_ I receive the following error:

```
[Exception]                                                                   
  DateTime::__construct(): Failed to parse time string (191232025916) at posit  
  ion 11 (6): Unexpected character   
```

I solved my problem by editing /src/Console/Update.php file.

Replace this line

`$timestamp = new DateTime(strtotime($content->timestamp));`

By this
```
$timestamp = new DateTime();
$timestamp->setTimestamp($content->timestamp);
```

I know that my solution is not the best since it'll be overwriten whhen I run _**composer update**_

**Comment by Torann** [comment]
Just released a patch for this
